fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,36 +25,36 @@ jobs:
           ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} ' 
           cd /home/fidesinnova-stg &&
           git checkout staging &&
-          git pull
+          git pull &&
 
           cd /home/fidesinnova-stg/backend &&
-          echo "Installing new packages for backend via npm..."
+          echo "Installing new packages for backend via npm..." && 
           if npm install; then
               echo "Packages for backend installed successfully."
           else
               echo "Error: Failed to install backend packages."
               exit 1
-          fi
-          echo "Building backend..."
+          fi && 
+          echo "Building backend..." && 
           if npm run build; then
               echo "Backend build completed successfully."
           else
               echo "Error: Backend build failed."
               exit 1
-          fi
+          fi && 
 
-          echo "Navigating to web_app..."
-          cd /home/fidesinnova-stg/web_app/Source_webapp  { echo "Error: Failed to navigate to web_app directory."; exit 1; }
+          echo "Navigating to web_app..." &&
+          cd /home/fidesinnova-stg/web_app/Source_webapp  { echo "Error: Failed to navigate to web_app directory."; exit 1; } &&
 
-          echo "Installing new packages for web_app via npm..."
+          echo "Installing new packages for web_app via npm..." &&
           if npm install; then
               echo "Packages for web_app installed successfully."
           else
               echo "Error: Failed to install web_app packages."
               exit 1
-          fi
+          fi &&
 
-          echo "Building web_app..."
+          echo "Building web_app..." &&
           if npm run build; then
               echo "web_app build completed successfully."
               echo "Cleaning up Runner_webapp frontend folder..."
@@ -72,11 +72,11 @@ jobs:
           else
               echo "Error: web_app build failed."
               exit 1
-          fi
+          fi &&
 
 
-          echo "Installing new packages for web_app/Runner_webapp..."
-          cd /home/fidesinnova-stg/web_app/Runner_webapp  { echo "Error: Failed to navigate to Runner_webapp directory."; exit 1; }
+          echo "Installing new packages for web_app/Runner_webapp..." &&
+          cd /home/fidesinnova-stg/web_app/Runner_webapp  { echo "Error: Failed to navigate to Runner_webapp directory."; exit 1; } &&
           if npm install; then
               echo "Packages of Runner_webapp for web_app installed successfully."
           else
